language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - docker build -t pedrowalter/tasklist-backend .
  - docker run -d -p 8000:8000 pedrowalter/tasklist-backend python manage.py runserver
  - docker ps -a
deploy:
  provider: script
  script: bash deploy_dockerhub.sh
  on:
    all_branches: true